/**
 * CodeGenerator — Design JSON → React TSX code generation
 *
 * Serializes the current canvas state (panels + components) into
 * clean, production-ready React component code with Tailwind CSS.
 */

import React, { useState, useCallback, useMemo } from 'react';
import {
  Code2, Copy, Check, Download, FileCode2, X,
  ChevronDown, ChevronRight, Layers, Sparkles
} from 'lucide-react';
import { useDesigner, COMPONENT_LIBRARY, type Panel, type ComponentInstance } from '../../store';
import { useThemeTokens } from './hooks/useThemeTokens';
import { copyToClipboard } from '../../utils/clipboard';
import { motion, AnimatePresence } from 'motion/react';

/* ================================================================
   Code Generation Engine
   ================================================================ */

function indent(code: string, level: number): string {
  const pad = '  '.repeat(level);
  return code.split('\n').map(l => l.trim() ? pad + l : '').join('\n');
}

function propsToJSX(props: Record<string, any>): string {
  const parts: string[] = [];
  for (const [key, val] of Object.entries(props)) {
    if (val === true) parts.push(key);
    else if (val === false) parts.push(`${key}={false}`);
    else if (typeof val === 'number') parts.push(`${key}={${val}}`);
    else if (typeof val === 'string') parts.push(`${key}="${val}"`);
    else if (Array.isArray(val)) parts.push(`${key}={${JSON.stringify(val)}}`);
    else if (typeof val === 'object') parts.push(`${key}={${JSON.stringify(val)}}`);
  }
  return parts.join(' ');
}

function componentToJSX(comp: ComponentInstance, level: number): string {
  const pad = '  '.repeat(level);
  const lib = COMPONENT_LIBRARY.find(c => c.type === comp.type);
  const tag = comp.type;
  const propsStr = propsToJSX(comp.props);

  // Some components render children text
  const textContent = comp.props.content || comp.props.label;
  if (textContent && ['Button', 'Text', 'Badge'].includes(comp.type)) {
    return `${pad}<${tag} ${propsStr.replace(`label="${textContent}"`, '').replace(`content="${textContent}"`, '').trim()}>\n${pad}  ${textContent}\n${pad}</${tag}>`;
  }

  return `${pad}<${tag} ${propsStr} />`;
}

function panelToJSX(
  panel: Panel,
  components: ComponentInstance[],
  level: number
): string {
  const pad = '  '.repeat(level);
  const panelComps = components.filter(c => c.panelId === panel.id);
  const innerLevel = level + 1;

  const childrenCode = panelComps
    .map(c => componentToJSX(c, innerLevel))
    .join('\n');

  return `${pad}{/* 面板: ${panel.name} (${panel.type}) */}\n${pad}<div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-4 space-y-3">\n${pad}  <h3 className="text-sm text-white/60 font-medium">${panel.name}</h3>\n${childrenCode}\n${pad}</div>`;
}

/** Generate full React component from Design JSON */
export function generateReactCode(
  panels: Panel[],
  components: ComponentInstance[],
  projectName: string
): string {
  const imports = new Set<string>();
  const usedTypes = new Set(components.map(c => c.type));

  // Add import lines
  imports.add("import React from 'react';");

  // Build component imports (from hypothetical component library)
  if (usedTypes.size > 0) {
    const typeList = Array.from(usedTypes).sort().join(', ');
    imports.add(`import { ${typeList} } from '@yyc3/components';`);
  }

  const importsCode = Array.from(imports).join('\n');

  // Generate panel grid layout
  const panelsCode = panels.map(p => panelToJSX(p, components, 3)).join('\n\n');

  // Calculate grid layout
  const gridCols = panels.length <= 2 ? panels.length : Math.min(3, panels.length);

  return `${importsCode}

/**
 * ${projectName}
 * 
 * Auto-generated by YANYUCLOUD (YYC³) Low-Code Designer
 * Generated: ${new Date().toISOString()}
 * Panels: ${panels.length} | Components: ${components.length}
 */

export default function ${projectName.replace(/[^a-zA-Z0-9]/g, '')}Page() {
  return (
    <div className="min-h-screen bg-[#0a0b10] text-white p-6">
      <header className="mb-6">
        <h1 className="text-xl font-semibold text-white/90">${projectName}</h1>
        <p className="text-sm text-white/40 mt-1">由 YYC³ 低码设计器自动生成</p>
      </header>

      <div className="grid grid-cols-${gridCols} gap-4">
${panelsCode}
      </div>
    </div>
  );
}
`;
}

/** Generate Design JSON export */
export function generateDesignJSON(
  panels: Panel[],
  components: ComponentInstance[],
  projectName: string
): string {
  return JSON.stringify({
    metadata: {
      project: projectName,
      version: '3.0.0',
      generator: 'YYC³ CloudPivot Intelli-Matrix',
      generatedAt: new Date().toISOString(),
    },
    theme: 'dark',
    panels: panels.map(p => ({
      id: p.id,
      name: p.name,
      type: p.type,
      layout: { x: p.x, y: p.y, w: p.w, h: p.h },
      children: components
        .filter(c => c.panelId === p.id)
        .map(c => ({
          id: c.id,
          type: c.type,
          label: c.label,
          props: c.props,
        })),
    })),
  }, null, 2);
}

/* ================================================================
   CodeGenerator Dialog
   ================================================================ */

export function CodeGeneratorDialog({ onClose }: { onClose: () => void }) {
  const t = useThemeTokens();
  const { panels, components, projectName } = useDesigner();
  const [activeTab, setActiveTab] = useState<'react' | 'json'>('react');
  const [copied, setCopied] = useState(false);
  const [expandedPanels, setExpandedPanels] = useState<Set<string>>(new Set(panels.map(p => p.id)));

  const reactCode = useMemo(
    () => generateReactCode(panels, components, projectName),
    [panels, components, projectName]
  );

  const jsonCode = useMemo(
    () => generateDesignJSON(panels, components, projectName),
    [panels, components, projectName]
  );

  const currentCode = activeTab === 'react' ? reactCode : jsonCode;

  const handleCopy = useCallback(() => {
    copyToClipboard(currentCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [currentCode]);

  const handleDownload = useCallback(() => {
    const filename = activeTab === 'react'
      ? `${projectName.replace(/[^a-zA-Z0-9]/g, '')}.tsx`
      : 'design.json';
    const blob = new Blob([currentCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }, [currentCode, activeTab, projectName]);

  const togglePanel = (id: string) => {
    setExpandedPanels(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  return (
    <motion.div
      className="fixed inset-0 z-[500] bg-black/60 backdrop-blur-sm flex items-center justify-center"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      onClick={onClose}
    >
      <motion.div
        className={`w-[720px] max-h-[85vh] ${t.panelBg} border ${t.panelBorder} rounded-2xl shadow-2xl overflow-hidden flex flex-col`}
        style={{ boxShadow: '0 24px 80px rgba(0,0,0,0.6), 0 0 120px rgba(99,102,241,0.08)' }}
        initial={{ scale: 0.95, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        transition={{ duration: 0.25 }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className={`flex items-center gap-3 px-5 py-4 border-b ${t.sectionBorder}`}>
          <div className={`w-8 h-8 rounded-xl ${t.accentBg} flex items-center justify-center`}>
            <Code2 className={`w-4 h-4 ${t.accent}`} />
          </div>
          <div className="flex-1">
            <h3 className={`text-[13px] ${t.textPrimary}`} style={{ fontWeight: 600 }}>代码生成器</h3>
            <p className={`text-[10px] ${t.textTertiary} mt-0.5`}>
              Design JSON → React TSX 全自动转换 · {panels.length} 面板 · {components.length} 组件
            </p>
          </div>

          {/* Tab switcher */}
          <div className={`flex items-center ${t.inputBg} rounded-lg p-0.5`}>
            <button
              onClick={() => setActiveTab('react')}
              className={`flex items-center gap-1 px-2.5 py-1 rounded-md text-[11px] transition-all ${
                activeTab === 'react'
                  ? `${t.accentBg} ${t.activeTabText}`
                  : `${t.textTertiary} hover:text-white/60`
              }`}
            >
              <FileCode2 className="w-3 h-3" />
              React TSX
            </button>
            <button
              onClick={() => setActiveTab('json')}
              className={`flex items-center gap-1 px-2.5 py-1 rounded-md text-[11px] transition-all ${
                activeTab === 'json'
                  ? `${t.accentBg} ${t.activeTabText}`
                  : `${t.textTertiary} hover:text-white/60`
              }`}
            >
              <Layers className="w-3 h-3" />
              Design JSON
            </button>
          </div>

          <button
            onClick={onClose}
            className={`p-1.5 rounded-md ${t.textMuted} hover:text-white/50 ${t.hoverBg}`}
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Structure overview sidebar + code */}
        <div className="flex flex-1 min-h-0">
          {/* Left: structure tree */}
          <div className={`w-[180px] border-r ${t.sectionBorder} p-3 overflow-y-auto shrink-0`}>
            <div className={`text-[9px] ${t.textMuted} uppercase tracking-wider mb-2`}>项目结构</div>
            {panels.map(p => {
              const panelComps = components.filter(c => c.panelId === p.id);
              const expanded = expandedPanels.has(p.id);
              return (
                <div key={p.id} className="mb-1">
                  <button
                    onClick={() => togglePanel(p.id)}
                    className={`w-full flex items-center gap-1.5 px-2 py-1.5 rounded-md text-left ${t.hoverBg} transition-colors`}
                  >
                    {expanded ? <ChevronDown className={`w-3 h-3 ${t.textMuted}`} /> : <ChevronRight className={`w-3 h-3 ${t.textMuted}`} />}
                    <Layers className={`w-3 h-3 ${t.accent} opacity-60`} />
                    <span className={`text-[11px] ${t.textSecondary} truncate`}>{p.name}</span>
                    <span className={`text-[9px] ${t.textMuted} ml-auto`}>{panelComps.length}</span>
                  </button>
                  {expanded && panelComps.map(c => (
                    <div key={c.id} className={`flex items-center gap-1.5 px-6 py-1 text-[10px] ${t.textTertiary}`}>
                      <Sparkles className="w-2.5 h-2.5 opacity-40" />
                      <span className="truncate">{c.label}</span>
                      <span className={`text-[8px] ${t.textMuted} ml-auto`}>{c.type}</span>
                    </div>
                  ))}
                </div>
              );
            })}
          </div>

          {/* Right: code preview */}
          <div className="flex-1 flex flex-col min-w-0">
            {/* Code toolbar */}
            <div className={`flex items-center gap-2 px-4 py-2 border-b ${t.sectionBorder}`}>
              <span className={`text-[10px] ${t.textMuted}`}>
                {activeTab === 'react' ? `${projectName}.tsx` : 'design.json'}
              </span>
              <div className="flex-1" />
              <button
                onClick={handleCopy}
                className={`flex items-center gap-1 px-2 py-1 rounded-md text-[10px] transition-all ${
                  copied
                    ? 'bg-emerald-500/20 text-emerald-400'
                    : `${t.hoverBg} ${t.textTertiary} hover:text-white/60`
                }`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? '已复制' : '复制'}
              </button>
              <button
                onClick={handleDownload}
                className={`flex items-center gap-1 px-2 py-1 rounded-md text-[10px] ${t.hoverBg} ${t.textTertiary} hover:text-white/60 transition-all`}
              >
                <Download className="w-3 h-3" />
                下载
              </button>
            </div>

            {/* Code area */}
            <div className="flex-1 overflow-auto p-4">
              <pre className={`text-[11px] leading-relaxed ${t.codeAccent || 'text-indigo-300/80'} whitespace-pre-wrap break-all font-mono`}>
                {currentCode}
              </pre>
            </div>

            {/* Stats footer */}
            <div className={`flex items-center gap-3 px-4 py-2 border-t ${t.sectionBorder}`}>
              <span className={`text-[9px] ${t.textMuted}`}>
                {currentCode.split('\n').length} 行
              </span>
              <span className={`text-[9px] ${t.textMuted}`}>
                {(currentCode.length / 1024).toFixed(1)} KB
              </span>
              <div className="flex-1" />
              <span className={`text-[9px] ${t.textMuted}`}>
                YYC³ CloudPivot · 设计即代码
              </span>
            </div>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
