/**
 * file: DeployPanel.tsx
 * description: 部署面板组件 — 项目部署配置和执行面板
 * author: YanYuCloudCube Team <admin@0379.email>
 * version: v1.0.0
 * created: 2026-03-08
 * updated: 2026-04-04
 * status: stable
 * tags: component,designer,deploy,panel
 */

import React, { useState } from 'react';
import {
  X, Rocket, Container, Globe, Shield, Key, RefreshCw,
  CheckCircle2, AlertTriangle, Copy, Check, Terminal,
  Server, Database, Wifi, Lock, Play,
  FileCode2, Settings2
} from 'lucide-react';
import { useDesigner } from '../../store';
import { copyToClipboard } from '../../utils/clipboard';
import { useThemeTokens } from './hooks/useThemeTokens';

/* ================================================================
   Docker Compose Generator
   ================================================================ */

function generateDockerCompose(projectName: string, panelCount: number, componentCount: number): string {
  return `# Auto-generated by YANYUCLOUD Low-Code Designer
# Project: ${projectName}
# Panels: ${panelCount} | Components: ${componentCount}
# Generated: ${new Date().toISOString()}

version: '3.8'

services:
  # Frontend — React + Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./design.json:/app/design.json:ro
      - ./frontend/src:/app/src
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_OPENAI_CLIENT_ID=\${OPENAI_CLIENT_ID}
      - VITE_OPENAI_REDIRECT_URI=http://localhost:5173/auth/callback
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend — Fastify + Prisma
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./design.json:/app/design.json:ro
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:./data/db.sqlite
      - JWT_SECRET=\${JWT_SECRET}
      - OPENAI_API_KEY=\${OPENAI_API_KEY}
      - OPENAI_CLIENT_ID=\${OPENAI_CLIENT_ID}
      - OPENAI_CLIENT_SECRET=\${OPENAI_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  # Real-time Collaboration — y-websocket
  yjs:
    build:
      context: ./yjs-server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
      - PORT=1234
    networks:
      - app-network
    restart: unless-stopped

  # Database — SQLite (dev) / MySQL (prod)
  db:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: ["tail", "-f", "/dev/null"]
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge`;
}

function generateEnvExample(): string {
  return `# YANYUCLOUD Low-Code Designer — Environment Variables
# Copy to .env and fill in your values

# ── Frontend ──
VITE_OPENAI_CLIENT_ID=your_openai_client_id
VITE_OPENAI_REDIRECT_URI=http://localhost:5173/auth/callback

# ── Backend ──
OPENAI_CLIENT_ID=your_openai_client_id
OPENAI_CLIENT_SECRET=your_openai_client_secret
OPENAI_API_KEY=sk-your-openai-api-key

# ── Database ──
# SQLite (default for local development)
DATABASE_URL="file:./data/db.sqlite"
# MySQL (uncomment for production)
# DATABASE_URL="mysql://user:password@db:3306/yanyucloud"

# ── Authentication ──
JWT_SECRET="your-super-secret-jwt-key-change-this"
JWT_EXPIRES_IN=7d

# ── CRDT Sync ──
YJS_HOST=0.0.0.0
YJS_PORT=1234`;
}

function generateNginxConf(): string {
  return `# YANYUCLOUD Nginx Reverse Proxy
server {
    listen 80;
    server_name localhost;

    # Frontend
    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Backend API
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # AI Proxy (unified auth)
    location /api/ai-proxy {
        proxy_pass http://backend:3000/api/ai-proxy;
        proxy_buffering off;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
    }

    # WebSocket (CRDT)
    location /yjs {
        proxy_pass http://yjs:1234;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}`;
}

/* ================================================================
   Deploy Steps
   ================================================================ */

interface DeployStep {
  id: string;
  label: string;
  desc: string;
  icon: React.ElementType;
  status: 'pending' | 'running' | 'done' | 'error';
  duration?: string;
}

/* ================================================================
   DeployPanel Component
   ================================================================ */

export function DeployPanel() {
  const { deployPanelOpen, toggleDeployPanel, panels, components, projectName } = useDesigner();
  const [activeTab, setActiveTab] = useState<'deploy' | 'docker' | 'env' | 'auth'>('deploy');
  const [deploying, setDeploying] = useState(false);
  const [copied, setCopied] = useState(false);
  const [steps, setSteps] = useState<DeployStep[]>([
    { id: 'validate', label: '校验 Design JSON', desc: 'Zod Schema 校验所有面板和组件配置', icon: CheckCircle2, status: 'pending' },
    { id: 'generate', label: '生成代码', desc: 'Handlebars 模板 → React TSX + 路由 + 状态', icon: FileCode2, status: 'pending' },
    { id: 'prisma', label: '同步数据库', desc: 'Prisma migrate → 生成 Client → CRUD API', icon: Database, status: 'pending' },
    { id: 'build', label: '构建前端', desc: 'Vite build → 产物写入 Docker Volume', icon: Container, status: 'pending' },
    { id: 'deploy', label: '容器部署', desc: 'docker compose up -d → 健康检查', icon: Rocket, status: 'pending' },
  ]);

  const t = useThemeTokens();

  if (!deployPanelOpen) return null;

  const handleCopy = (text: string) => {
    copyToClipboard(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDeploy = () => {
    setDeploying(true);
    const durations = ['0.3s', '1.2s', '0.8s', '4.5s', '2.1s'];
    let idx = 0;
    const interval = setInterval(() => {
      if (idx < steps.length) {
        setSteps(prev => prev.map((s, i) =>
          i === idx ? { ...s, status: 'running' } :
          i < idx ? { ...s, status: 'done', duration: durations[i] } : s
        ));
        idx++;
      } else {
        setSteps(prev => prev.map((s, i) => ({ ...s, status: 'done', duration: durations[i] })));
        setDeploying(false);
        clearInterval(interval);
      }
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center">
      <div className={`absolute inset-0 ${t.overlayBg} backdrop-blur-md`} onClick={toggleDeployPanel} />
      <div
        className={`relative w-[720px] max-h-[85vh] ${t.modalBg} border ${t.modalBorder} rounded-2xl flex flex-col overflow-hidden`}
        style={{ boxShadow: t.modalShadow }}
      >
        {/* Header */}
        <div className={`flex items-center gap-3 px-5 py-4 border-b ${t.sectionBorder}`}>
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-emerald-500/20 to-teal-500/20 border border-emerald-500/20 flex items-center justify-center">
            <Rocket className="w-4 h-4 text-emerald-400" />
          </div>
          <div className="flex-1">
            <div className={`text-[14px] ${t.textPrimary}`}>配置即部署</div>
            <div className={`text-[11px] ${t.textTertiary}`}>Design JSON → 代码生成 → Docker 容器化部署</div>
          </div>
          <button onClick={toggleDeployPanel} className={`p-2 rounded-lg ${t.textMuted} hover:text-white/60 ${t.hoverBg} transition-all`}>
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tabs */}
        <div className={`flex gap-1 px-5 pt-3 pb-0 border-b ${t.sectionBorder}`}>
          {([
            { key: 'deploy' as const, label: '部署流程', icon: Play },
            { key: 'docker' as const, label: 'Docker Compose', icon: Container },
            { key: 'env' as const, label: '环境变量', icon: Terminal },
            { key: 'auth' as const, label: '认证配置', icon: Shield },
          ]).map(({ key, label, icon: Icon }) => (
            <button
              key={key}
              onClick={() => setActiveTab(key)}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-t-lg text-[12px] transition-all border-b-2 ${
                activeTab === key
                  ? `${t.activeTabText} border-current ${t.activeBg}`
                  : `${t.textTertiary} border-transparent hover:text-white/50`
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              {label}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5 min-h-0">
          {activeTab === 'deploy' && (
            <div className="space-y-4">
              {/* Project summary */}
              <div className={`flex items-center gap-4 p-4 rounded-xl ${t.surfaceInset} border ${t.surfaceInsetBorder}`}>
                <div>
                  <div className={`text-[12px] ${t.textSecondary}`}>{projectName}</div>
                  <div className={`text-[10px] ${t.textMuted} mt-0.5`}>{panels.length} 面板 · {components.length} 组件 · React TSX</div>
                </div>
                <div className="ml-auto flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-emerald-400" />
                  <span className="text-[10px] text-emerald-400">Schema Valid</span>
                </div>
              </div>

              {/* Deploy steps */}
              <div className="space-y-2">
                {steps.map((step, idx) => (
                  <div
                    key={step.id}
                    className={`flex items-center gap-3 p-3 rounded-xl border transition-all ${
                      step.status === 'done' ? 'border-emerald-500/20 bg-emerald-500/[0.03]' :
                      step.status === 'running' ? 'border-amber-500/20 bg-amber-500/[0.03]' :
                      'border-white/[0.06] bg-white/[0.01]'
                    }`}
                  >
                    <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${
                      step.status === 'done' ? 'bg-emerald-500/15' :
                      step.status === 'running' ? 'bg-amber-500/15' :
                      'bg-white/[0.04]'
                    }`}>
                      {step.status === 'done' ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> :
                       step.status === 'running' ? <RefreshCw className="w-4 h-4 text-amber-400 animate-spin" /> :
                       <step.icon className="w-4 h-4 text-white/20" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-[12px] text-white/70">{idx + 1}. {step.label}</div>
                      <div className="text-[10px] text-white/25">{step.desc}</div>
                    </div>
                    {step.duration && (
                      <span className="text-[9px] text-emerald-400/60 bg-emerald-500/[0.06] px-2 py-0.5 rounded">{step.duration}</span>
                    )}
                  </div>
                ))}
              </div>

              {/* Deploy button */}
              <button
                onClick={handleDeploy}
                disabled={deploying}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-gradient-to-r from-emerald-500/20 to-teal-500/20 border border-emerald-500/25 text-emerald-400 text-[13px] hover:from-emerald-500/30 hover:to-teal-500/30 transition-all disabled:opacity-50"
              >
                {deploying ? (
                  <><RefreshCw className="w-4 h-4 animate-spin" /> 部署中...</>
                ) : steps.every(s => s.status === 'done') ? (
                  <><CheckCircle2 className="w-4 h-4" /> 部署完成 — 访问 localhost:5173</>
                ) : (
                  <><Rocket className="w-4 h-4" /> 一键部署到容器</>
                )}
              </button>

              {steps.every(s => s.status === 'done') && (
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { label: '前端', url: 'http://localhost:5173', icon: Globe, color: 'text-blue-400' },
                    { label: 'API', url: 'http://localhost:3000', icon: Server, color: 'text-amber-400' },
                    { label: 'WebSocket', url: 'ws://localhost:1234', icon: Wifi, color: 'text-cyan-400' },
                  ].map(svc => (
                    <div key={svc.label} className="p-3 rounded-xl border border-white/[0.06] bg-white/[0.02]">
                      <div className="flex items-center gap-2">
                        <svc.icon className={`w-3.5 h-3.5 ${svc.color}`} />
                        <span className="text-[11px] text-white/60">{svc.label}</span>
                      </div>
                      <div className="text-[9px] text-white/25 font-mono mt-1 truncate">{svc.url}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {activeTab === 'docker' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between mb-2">
                <span className="text-[12px] text-white/70">docker-compose.yml</span>
                <button
                  onClick={() => handleCopy(generateDockerCompose(projectName, panels.length, components.length))}
                  className="flex items-center gap-1 px-2.5 py-1 rounded-lg text-[10px] text-white/30 hover:text-white/60 hover:bg-white/[0.06]"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  {copied ? '已复制' : '复制'}
                </button>
              </div>
              <div className="rounded-xl border border-white/[0.06] overflow-hidden">
                <pre className="p-4 text-[10px] leading-relaxed font-mono text-white/40 overflow-x-auto">
                  {generateDockerCompose(projectName, panels.length, components.length)}
                </pre>
              </div>
              <div className="flex items-center justify-between mt-3 mb-2">
                <span className="text-[12px] text-white/70">nginx.conf</span>
                <button
                  onClick={() => handleCopy(generateNginxConf())}
                  className="flex items-center gap-1 px-2.5 py-1 rounded-lg text-[10px] text-white/30 hover:text-white/60 hover:bg-white/[0.06]"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  {copied ? '已复制' : '复制'}
                </button>
              </div>
              <div className="rounded-xl border border-white/[0.06] overflow-hidden">
                <pre className="p-4 text-[10px] leading-relaxed font-mono text-white/40 overflow-x-auto">
                  {generateNginxConf()}
                </pre>
              </div>
            </div>
          )}

          {activeTab === 'env' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between mb-2">
                <span className="text-[12px] text-white/70">.env.example</span>
                <button
                  onClick={() => handleCopy(generateEnvExample())}
                  className="flex items-center gap-1 px-2.5 py-1 rounded-lg text-[10px] text-white/30 hover:text-white/60 hover:bg-white/[0.06]"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  {copied ? '已复制' : '复制'}
                </button>
              </div>
              <div className="rounded-xl border border-white/[0.06] overflow-hidden">
                <pre className="p-4 text-[10px] leading-relaxed font-mono text-white/40 overflow-x-auto">
                  {generateEnvExample()}
                </pre>
              </div>
              <div className="p-3 rounded-xl bg-amber-500/[0.06] border border-amber-500/15 flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                <div>
                  <div className="text-[11px] text-amber-400/80">安全提醒</div>
                  <div className="text-[10px] text-white/30 mt-1 leading-relaxed">
                    .env 文件包含敏感信息，请勿提交到版本控制。生产环境建议使用 Docker Secrets 或 Vault。
                  </div>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'auth' && (
            <div className="space-y-4">
              {/* OpenID Connect Config */}
              <div className="rounded-xl border border-white/[0.06] overflow-hidden">
                <div className="px-4 py-3 bg-white/[0.02] border-b border-white/[0.06] flex items-center gap-2">
                  <Shield className="w-4 h-4 text-indigo-400" />
                  <span className="text-[12px] text-white/70">OpenID Connect (OpenAI OAuth)</span>
                </div>
                <div className="p-4 space-y-3">
                  {[
                    { label: 'Client ID', placeholder: 'your_openai_client_id', type: 'text' },
                    { label: 'Client Secret', placeholder: 'your_openai_client_secret', type: 'password' },
                    { label: 'Redirect URI', placeholder: 'http://localhost:5173/auth/callback', type: 'text' },
                    { label: 'Authorization URL', placeholder: 'https://auth.openai.com/authorize', type: 'text' },
                    { label: 'Token URL', placeholder: 'https://auth.openai.com/token', type: 'text' },
                  ].map(field => (
                    <div key={field.label}>
                      <label className="text-[10px] text-white/30 uppercase tracking-wider mb-1 block">{field.label}</label>
                      <input
                        type={field.type}
                        placeholder={field.placeholder}
                        className="w-full bg-white/[0.04] border border-white/[0.06] rounded-lg px-3 py-2 text-[11px] text-white/60 placeholder:text-white/15 focus:outline-none focus:border-indigo-500/30 font-mono"
                      />
                    </div>
                  ))}
                </div>
              </div>

              {/* JWT Config */}
              <div className="rounded-xl border border-white/[0.06] overflow-hidden">
                <div className="px-4 py-3 bg-white/[0.02] border-b border-white/[0.06] flex items-center gap-2">
                  <Key className="w-4 h-4 text-amber-400" />
                  <span className="text-[12px] text-white/70">JWT 令牌配置</span>
                </div>
                <div className="p-4 space-y-3">
                  <div>
                    <label className="text-[10px] text-white/30 uppercase tracking-wider mb-1 block">JWT Secret</label>
                    <input type="password" placeholder="your-super-secret-jwt-key" className="w-full bg-white/[0.04] border border-white/[0.06] rounded-lg px-3 py-2 text-[11px] text-white/60 placeholder:text-white/15 focus:outline-none focus:border-amber-500/30 font-mono" />
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-[10px] text-white/30 uppercase tracking-wider mb-1 block">过期时间</label>
                      <input defaultValue="7d" className="w-full bg-white/[0.04] border border-white/[0.06] rounded-lg px-3 py-2 text-[11px] text-white/60 focus:outline-none focus:border-amber-500/30 font-mono" />
                    </div>
                    <div>
                      <label className="text-[10px] text-white/30 uppercase tracking-wider mb-1 block">签名算法</label>
                      <select className="w-full bg-white/[0.04] border border-white/[0.06] rounded-lg px-3 py-2 text-[11px] text-white/60 appearance-none" style={{ backgroundImage: 'none' }}>
                        <option className="bg-[#1a1b2e]">HS256</option>
                        <option className="bg-[#1a1b2e]">RS256</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>

              {/* RBAC */}
              <div className="rounded-xl border border-white/[0.06] overflow-hidden">
                <div className="px-4 py-3 bg-white/[0.02] border-b border-white/[0.06] flex items-center gap-2">
                  <Lock className="w-4 h-4 text-emerald-400" />
                  <span className="text-[12px] text-white/70">RBAC 角色权限</span>
                </div>
                <div className="p-4">
                  <div className="space-y-2">
                    {[
                      { role: 'ADMIN', perms: '全部权限 — 面板管理、用户管理、部署', color: 'text-red-400 bg-red-500/10' },
                      { role: 'EDITOR', perms: '编辑面板、组件、数据绑定', color: 'text-amber-400 bg-amber-500/10' },
                      { role: 'VIEWER', perms: '只读访问 — 预览和导出代码', color: 'text-blue-400 bg-blue-500/10' },
                    ].map(r => (
                      <div key={r.role} className="flex items-center gap-3 p-2.5 rounded-lg bg-white/[0.02]">
                        <span className={`text-[10px] px-2 py-0.5 rounded ${r.color}`}>{r.role}</span>
                        <span className="text-[10px] text-white/40">{r.perms}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* AI Proxy */}
              <div className="rounded-xl border border-white/[0.06] overflow-hidden">
                <div className="px-4 py-3 bg-white/[0.02] border-b border-white/[0.06] flex items-center gap-2">
                  <Settings2 className="w-4 h-4 text-purple-400" />
                  <span className="text-[12px] text-white/70">AI 代理 (/api/ai-proxy)</span>
                </div>
                <div className="p-4 space-y-2">
                  <div className="text-[10px] text-white/30 leading-relaxed">
                    所有 AI 请求通过后端 <code className="text-purple-300/60 bg-white/[0.04] px-1 py-0.5 rounded">/api/ai-proxy</code> 统一转发。
                    后端自动注入 <code className="text-purple-300/60 bg-white/[0.04] px-1 py-0.5 rounded">Authorization: Bearer</code> 并计量 token 消耗。
                  </div>
                  <div className="flex items-center gap-2 p-2 rounded-lg bg-purple-500/[0.04] border border-purple-500/10">
                    <CheckCircle2 className="w-3.5 h-3.5 text-purple-400" />
                    <span className="text-[10px] text-purple-400/70">支持 SSE 流式转发 · 统一错误包装 · Token 计量</span>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className={`flex items-center justify-between px-5 py-3 border-t ${t.sectionBorder} ${t.surfaceInset}`}>
          <span className={`text-[10px] ${t.textMuted}`}>
            Docker Compose + Nginx + Prisma + Fastify + y-websocket
          </span>
          <button onClick={toggleDeployPanel} className={`px-4 py-1.5 rounded-lg ${t.badgeBg} ${t.textTertiary} text-[11px] ${t.hoverBg} transition-all`}>
            完成
          </button>
        </div>
      </div>
    </div>
  );
}